"""Copy for Agent (spec §3.5 / §6.3-H): Material Pack -> Agent-readable Markdown / JSON.

The Markdown is meant to be pasted into ChatGPT / Claude / Cursor as context, so it
carries what an agent cannot see for itself: the human's thought, why the material
was chosen for this task, the machine description of images, quoted text, and sources.
"""

from __future__ import annotations

from .db import Database
from .models import Material, MaterialPack


def _label(m: Material) -> str:
    return m.source.page_title or m.original.filename or m.short_label()


def _material_block(idx: int, m: Material, role: str | None, reason: str | None, note: str | None, added_by: str) -> str:
    a = m.analysis
    out = [f"### {idx}. {_label(m)}", f"*{m.modality} · `{m.id}`" + (f" · role: {role}" if role else "") + (" · added by the human" if added_by == "human" else "") + "*", ""]
    if m.human.thought:
        out += ["Human Thought:", f"> {m.human.thought}", ""]
    if reason:
        out += ["Why selected:", reason, ""]
    if note:
        out += ["Human note for this task:", note, ""]
    ai = []
    if a.summary:
        ai.append(a.summary)
    tags = [*a.style[:5], *[k for k in a.keywords[:6] if k not in a.style]]
    if tags:
        ai.append("Keywords: " + ", ".join(tags))
    if m.modality == "image":
        pal = (m.objective_metadata.get("palette") or {}).get("descriptors") or []
        cols = [f"{c.hex} ({c.name}, {c.ratio:.0%})" for c in a.colors[:4]]
        if pal or cols:
            ai.append("Palette: " + ", ".join(pal) + (" — " + ", ".join(cols) if cols else ""))
        if a.ocr:
            ai.append("Text in image: " + a.ocr.replace("\n", " / ")[:300])
    if ai:
        out += ["What it is (AI analysis):", *[f"- {x}" for x in ai], ""]
    if m.modality == "text" and m.original.content:
        txt = m.original.content.strip()
        if len(txt) > 700:
            txt = txt[:700].rstrip() + " …"
        out += ["Text:", *[f"> {line}" for line in txt.splitlines()], ""]
    src = []
    if m.source.page_url:
        src.append(f"- Source page: {m.source.page_url}" + (f" ({m.source.page_title})" if m.source.page_title else ""))
    if m.source.resource_url and m.source.resource_url != m.source.page_url:
        src.append(f"- Original file: {m.source.resource_url}")
    if m.original.filename and m.modality == "image":
        src.append(f"- Local file: {m.original.filename} (`GET /materials/{m.id}/file`)")
    if m.source.license:
        src.append(f"- License: {m.source.license}")
    if src:
        out += ["Source:", *src, ""]
    return "\n".join(out)


def pack_to_markdown(pack: MaterialPack, db: Database) -> str:
    mats = db.get_materials(pack.member_ids())
    t = pack.task
    lines = ["# Task", t.raw_request, ""]
    lines += ["## Human Direction"]
    if pack.human_direction:
        lines += [pack.human_direction, ""]
    if t.purpose:
        lines.append(f"- Purpose: {t.purpose}")
    if t.desired_qualities:
        lines.append("- Go for: " + "、".join(t.desired_qualities))
    if t.avoid:
        lines.append("- Avoid: " + "、".join(t.avoid))
    if t.constraints:
        lines.append("- Constraints: " + "、".join(t.constraints))
    if pack.gaps:
        lines.append("- Not in the library (gaps): " + " ".join(pack.gaps))
    lines.append("")
    idx = 0
    for g in pack.groups:
        members = [m for m in g.members if m.material_id in mats]
        if not members:
            continue
        lines.append(f"## {g.name}")
        if g.purpose:
            lines.append(f"_{g.purpose}_")
        lines.append("")
        for mem in members:
            idx += 1
            lines.append(_material_block(idx, mats[mem.material_id], mem.role, mem.reason, mem.note, mem.added_by))
    if pack.removed_material_ids:
        lines += ["## Deliberately left out by the human", "The following saved materials were removed from this pack on purpose; do not re-introduce them:"]
        removed = db.get_materials(pack.removed_material_ids)
        for rid in pack.removed_material_ids:
            m = removed.get(rid)
            lines.append(f"- `{rid}`" + (f" — {_label(m)}" if m else ""))
        lines.append("")
    lines += [
        "---",
        f"Generated by Magpie · pack `{pack.id}` · {idx} materials · {len(pack.human_edits)} human edits · {pack.updated_at}",
        "Use the Human Thoughts and 'Why selected' notes as design intent; the AI analysis describes what each image looks like.",
    ]
    return "\n".join(lines).strip() + "\n"


def pack_to_json(pack: MaterialPack, db: Database) -> dict:
    mats = db.get_materials(pack.member_ids() + pack.removed_material_ids)

    def mat(m: Material) -> dict:
        return {
            "id": m.id,
            "modality": m.modality,
            "label": _label(m),
            "human_thought": m.human.thought,
            "summary": m.analysis.summary,
            "style": m.analysis.style,
            "keywords": m.analysis.keywords,
            "mood": m.analysis.mood,
            "colors": [c.model_dump() for c in m.analysis.colors[:6]],
            "palette": (m.objective_metadata.get("palette") or {}).get("descriptors"),
            "text": m.original.content,
            "text_in_image": m.analysis.ocr,
            "source": m.source.model_dump(),
            "file_endpoint": f"/materials/{m.id}/file" if m.original.file_path else None,
        }

    return {
        "magpie_pack": {
            "id": pack.id,
            "name": pack.name,
            "created_at": pack.created_at,
            "updated_at": pack.updated_at,
            "task": pack.task.model_dump(),
            "human_direction": pack.human_direction,
            "gaps": pack.gaps,
            "groups": [
                {
                    "name": g.name,
                    "purpose": g.purpose,
                    "members": [
                        {"role": mem.role, "reason": mem.reason, "relevance": mem.relevance, "note": mem.note, "added_by": mem.added_by, "material": mat(mats[mem.material_id])}
                        for mem in g.members
                        if mem.material_id in mats
                    ],
                }
                for g in pack.groups
                if g.members
            ],
            "removed_by_human": [{"id": rid, "label": _label(mats[rid])} for rid in pack.removed_material_ids if rid in mats],
            "human_edits": [e.model_dump() for e in pack.human_edits],
        }
    }
